name: uni_drive
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-146.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^7.1.1
  google_maps_flutter: ^2.3.1
  google_maps_webservice: ^0.0.19
  http: ^1.0.0
  provider: ^6.0.5
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
